server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: persistence-service
            uri: lb://persistence-service
            predicates:
              - Path=/api/v1/persistence/**
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/v1/user/**